# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Review

# Model Form Field configuration
form: $/eugene3993/reviews/models/review/fields.yaml

# Model Class name
modelClass: Eugene3993\Reviews\Models\Review

# Default redirect location
defaultRedirect: eugene3993/reviews/reviews

# Create page
create:
    title: Create Simple Review
    redirect: eugene3993/reviews/reviews/update/:id
    redirectClose: eugene3993/reviews/reviews
    flashSave: 'Отзыв сохранен'

# Update page
update:
    title: 'Редактирование отзыва'
    redirect: eugene3993/reviews/reviews
    redirectClose: eugene3993/reviews/reviews
    flashSave: 'Отзыв сохранен'
    flashDelete: 'Отзыв удален'
