# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Review

# Model Form Field configuration
form: $/eugene3993/reviews/models/review/fields.yaml

# Model Class name
modelClass: Eugene3993\Reviews\Models\Review

# Default redirect location
defaultRedirect: eugene3993/reviews/reviews

# Create page
create:
    title: 'eugene3993.reviews::lang.page_title.create'
    redirect: eugene3993/reviews/reviews/update/:id
    redirectClose: eugene3993/reviews/reviews
    flashSave: 'eugene3993.reviews::lang.messages.save'

# Update page
update:
    title: 'eugene3993.reviews::lang.page_title.edit'
    redirect: eugene3993/reviews/reviews
    redirectClose: eugene3993/reviews/reviews
    flashSave: 'eugene3993.reviews::lang.messages.save'
    flashDelete: 'eugene3993.reviews::lang.messages.remove'
